/* LOGIN */
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

/* SIGNUP */
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'
export const SIGNUP_TYPE = 'SIGNUP_TYPE'

/* TALENT */
export const GET_ROLES_TECH = "GET_ROLES_TECH"
export const GET_SUBMITION_DATA = "GET_SUBMITION_DATA"
export const UPDATE_STATUS = "UPDATE_STATUS"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"
export const SUBMIT_SUCCESS = 'SUBMIT_SUCCESS'

/* USER */
export const GET_USER = "GET_USER"
export const EDIT_TYPE = "EDIT_TYPE"

