const images = {
    background : '/assets/images/background.jpg',
    triangle : '/assets/svgs/checkered_pattern.svg',
    clock : '/assets/icons/clock.png',
    user: '/assets/images/user.png',
    employer : '/assets/svgs/employer.svg',
    talent : '/assets/svgs/talent.svg',
    hambugerButton : '/assets/svgs/menu.svg',
    xButton: '/assets/svgs/xButton.svg',
    login : '/assets/svgs/login.svg',
    facebook_home: '/assets/svgs/facebook.svg',
    facebook : '/assets/svgs/facebook-icon.svg',
    linkedin_home: '/assets/svgs/linkedin.svg',
    linkedin : '/assets/svgs/linkedin-icon.svg',
    check : '/assets/svgs/checkmark.svg',
    google : '/assets/svgs/google-icon.svg',
    google1 : '/assets/svgs/google-icon1.svg',
    facebook1: '/assets/svgs/facebook-icon1.svg',
    warnning: '/assets/svgs/alert.svg',
    wRightArrow: '/assets/svgs/white-arrow.svg',
    leftArrow: '/assets/svgs/left-arrow.svg',
    bRightArrow: '/assets/svgs/model_arrow_right.svg',
    verticalArrow: '/assets/svgs/model_arrow_down.svg',
    remove: '/assets/svgs/cross-icon.svg',
    github: '/assets/svgs/github-icon.svg',
    behance: '/assets/svgs/behance-icon.svg',
    hoverMenu: '/assets/svgs/menu_hover.svg',
    loginHover: '/assets/svgs/login_hover.svg',
    arrowDown: '/assets/svgs/arrow_down.svg',
    logo_footer: '/assets/svgs/logo_footer.svg',
    logo_home: '/assets/svgs/logo_home.svg',
    aboutUs: '/assets/images/about.png',
    marker: '/assets/images/marker1.png',
    slider: '/assets/svgs/slider.svg'
}

export default images;